# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-16 07:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import ssms.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ssms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('gm_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Event UUID')),
                ('name', models.CharField(max_length=32, verbose_name='Event Name')),
                ('meal', models.CharField(choices=[('Workshop', 'Workshop'), ('Prof Shows', 'Prof Shows')], default='Veg', max_length=16, verbose_name='Event Type')),
                ('reg_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Registration Date')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('deadline', models.DateField(default=datetime.datetime.now)),
                ('deadline2', models.DateField(default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=128)),
                ('excel', models.FileField(upload_to=ssms.models.content_album_name)),
                ('mails', models.CharField(choices=[('Sent', 'Sent'), ('Not Sent', 'Not Sent')], default='Not Sent', max_length=128)),
                ('cg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssms.Grub_Coord', verbose_name='Coordinator Id')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Student',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique Student Id')),
                ('name', models.CharField(max_length=32)),
                ('student_id', models.CharField(max_length=32, verbose_name='Bits Id')),
                ('user_id', models.CharField(db_index=True, max_length=32, verbose_name='Bits Email Id')),
                ('mail', models.CharField(choices=[('Sent', 'Sent'), ('Not Sent', 'Not Sent')], default='Not Sent', max_length=128)),
                ('status', models.CharField(choices=[('Signed Up', 'Signed Up'), ('Opted Out', 'Opted Out')], max_length=128)),
                ('room', models.CharField(default='303', max_length=32, verbose_name='Room No.')),
                ('bhawan', models.CharField(default='VK', max_length=32, verbose_name='Bhawan')),
                ('gm_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ssms.Event', verbose_name='Event Id')),
            ],
        ),
        migrations.CreateModel(
            name='Wear',
            fields=[
                ('gm_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Wear UUID')),
                ('name', models.CharField(max_length=32, verbose_name='Wear Name')),
                ('meal', models.CharField(choices=[('T Shirt', 'T Shirt'), ('Sweat Shirt', 'Sweat Shirt')], default='Veg', max_length=16, verbose_name='Wear Type')),
                ('reg_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Registration Date')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('deadline', models.DateField(default=datetime.datetime.now)),
                ('deadline2', models.DateField(default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=128)),
                ('excel', models.FileField(upload_to=ssms.models.content_album_name)),
                ('mails', models.CharField(choices=[('Sent', 'Sent'), ('Not Sent', 'Not Sent')], default='Not Sent', max_length=128)),
                ('cg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssms.Grub_Coord', verbose_name='Coordinator Id')),
            ],
        ),
        migrations.CreateModel(
            name='Wear_Student',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique Student Id')),
                ('name', models.CharField(max_length=32)),
                ('student_id', models.CharField(max_length=32, verbose_name='Bits Id')),
                ('user_id', models.CharField(db_index=True, max_length=32, verbose_name='Bits Email Id')),
                ('mail', models.CharField(choices=[('Sent', 'Sent'), ('Not Sent', 'Not Sent')], default='Not Sent', max_length=128)),
                ('meal', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='Veg', max_length=16, verbose_name='Size Selected')),
                ('status', models.CharField(choices=[('Signed Up', 'Signed Up'), ('Opted Out', 'Opted Out')], max_length=128)),
                ('room', models.CharField(default='303', max_length=32, verbose_name='Room No.')),
                ('bhawan', models.CharField(default='VK', max_length=32, verbose_name='Bhawan')),
                ('gm_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ssms.Wear', verbose_name='Wear Id')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='wear_student',
            unique_together=set([('student_id', 'gm_id', 'status')]),
        ),
        migrations.AlterUniqueTogether(
            name='event_student',
            unique_together=set([('student_id', 'gm_id', 'status')]),
        ),
    ]
