# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-16 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import ssms.models


class Migration(migrations.Migration):

    dependencies = [
        ('ssms', '0002_auto_20170216_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='1', upload_to=ssms.models.content_album_name2, verbose_name='Event image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Event Price'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(default='1', max_length=16, verbose_name='Event Venue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_student',
            name='meal',
            field=models.CharField(choices=[('Workshop', 'Workshop'), ('Prof Shows', 'Prof Shows')], default='Veg', max_length=16, verbose_name='Size Selected'),
        ),
        migrations.AddField(
            model_name='wear',
            name='image',
            field=models.ImageField(default='1', upload_to=ssms.models.content_album_name2, verbose_name='Event image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wear',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Event Price'),
        ),
    ]
