# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-16 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import ssms.models


class Migration(migrations.Migration):

    dependencies = [
        ('ssms', '0003_auto_20170216_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to=ssms.models.content_album_name, verbose_name='Event image'),
        ),
        migrations.AlterField(
            model_name='wear',
            name='image',
            field=models.ImageField(upload_to=ssms.models.content_album_name, verbose_name='Wear image'),
        ),
        migrations.AlterField(
            model_name='wear',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Wear Price'),
        ),
    ]
